# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-enter = 'exec-and-forget open -na /Applications/kitty.app'
alt-space = 'exec-and-forget open -na "/Applications/Brave Browser.app"'
alt-m = 'exec-and-forget open -a "/Applications/Spotify.app"'
alt-s = 'exec-and-forget open -a "/Applications/Slack.app"'
alt-o = 'exec-and-forget open -a "/Applications/Obsidian.app"'
alt-w = 'exec-and-forget open -a "/Applications/WhatsApp.app"'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'split horizontal'
alt-backslash = 'split vertical'

alt-f = 'fullscreen'

alt-t = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-shift-equal = 'workspace 1'
alt-leftSquareBracket = 'workspace 2'
alt-shift-leftSquareBracket = 'workspace 3'
alt-shift-9 = 'workspace 4'
alt-shift-7 = 'workspace 5'
alt-equal = 'workspace 6'
alt-shift-0 = 'workspace 7'
alt-shift-rightSquareBracket = 'workspace 8'
alt-rightSquareBracket = 'workspace 9'
alt-shift-8 = 'workspace 10'

alt-1 = 'move-node-to-workspace 1'
alt-2 = 'move-node-to-workspace 2'
alt-3 = 'move-node-to-workspace 3'
alt-4 = 'move-node-to-workspace 4'
alt-5 = 'move-node-to-workspace 5'
alt-6 = 'move-node-to-workspace 6'
alt-7 = 'move-node-to-workspace 7'
alt-8 = 'move-node-to-workspace 8'
alt-9 = 'move-node-to-workspace 9'
alt-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
k = 'resize height +50'
j = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
